# Generated by Django 3.2.6 on 2021-08-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsappApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerpage',
            name='msg',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
