# Generated by Django 3.2.6 on 2021-08-12 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsappApi', '0002_registerpage_msg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerpage',
            old_name='msg',
            new_name='message',
        ),
    ]
